# Note: The value of secrets must be Base64-encoded.
# You can encode it using the following command:
# echo -n "your-actual-api-key" | base64
apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: "<Base64-encoded-API-Key>"
---
apiVersion: v1
kind: Secret
metadata:
  name: service-bus-secret
type: Opaque
data:
  SERVICE_BUS_SENDER_SECRET: "<Base64-encoded-Service-Bus-Sender-Key>"
  SERVICE_BUS_LISTENER_SECRET: "<Base64-encoded-Service-Bus-Listener-Key>"

